export const queryKeys = {
  dashboard: ['dashboard', 'stats'] as const,
  openExceptions: (limit: number) => ['exceptions', 'open', limit] as const,
  recentShipments: (limit: number) => ['shipments', 'recent', limit] as const,
  approvals: (status: string) => ['approvals', status] as const,
  approvalDetail: (id: string) => ['approvals', 'detail', id] as const,
  shipments: (params: Record<string, unknown>) => ['shipments', 'list', params] as const,
  shipmentDetail: (id: string) => ['shipments', 'detail', id] as const,
  shipmentDocuments: (id: string) => ['shipments', id, 'documents'] as const,
  shipmentMilestones: (id: string) => ['shipments', id, 'milestones'] as const,
  shipmentCommunications: (id: string) => ['shipments', id, 'communications'] as const,
  shipmentExceptions: (id: string) => ['shipments', id, 'exceptions'] as const,
  shipmentAssignments: (id: string) => ['shipments', id, 'assignments'] as const,
  shipmentAutomation: (id: string) => ['shipments', id, 'automation'] as const,
  shipmentQuotes: (id: string) => ['shipments', id, 'quotes'] as const,
  assignments: (params: Record<string, unknown>) => ['assignments', params] as const,
  agentsAvailable: ['agents', 'available'] as const,
  warehouseBays: (warehouseId?: string) => ['warehouse', 'bays', warehouseId] as const,
  warehouseInventory: (warehouseId?: string, status?: string) => ['warehouse', 'inventory', warehouseId, status] as const,
  documents: (params: Record<string, unknown>) => ['documents', params] as const,
  customers: (params: Record<string, unknown>) => ['customers', params] as const,
  customerDetail: (id: string) => ['customers', 'detail', id] as const,
  customerShipments: (id: string) => ['customers', id, 'shipments'] as const,
  rateCards: (params: Record<string, unknown>) => ['rate-cards', params] as const,
  automationControls: ['automation', 'controls'] as const,
  automationHistory: ['automation', 'history'] as const,
  users: ['users'] as const,
  exceptions: (params: Record<string, unknown>) => ['exceptions', 'list', params] as const,
  carriers: ['carriers'] as const,
  ddSaved: ['analytics', 'dd-saved'] as const,
  // New
  laneStats: (params: Record<string, unknown>) => ['vendor-intel', 'lane-stats', params] as const,
  carrierPerformance: (carrierId: string, from: string, to: string) => ['vendor-intel', 'carrier-perf', carrierId, from, to] as const,
  vendorSuggestions: (shipmentId: string) => ['vendor-intel', 'suggestions', shipmentId] as const,
  vendorQuotes: (params: Record<string, unknown>) => ['vendor-quotes', params] as const,
  vendorQuoteDetail: (id: string) => ['vendor-quotes', 'detail', id] as const,
  laneCheck: (params: Record<string, unknown>) => ['vendor-quotes', 'lane-check', params] as const,
  escalations: (params: Record<string, unknown>) => ['escalations', params] as const,
  escalationCount: ['escalations', 'count'] as const,
  approvalSummary: ['approvals', 'summary'] as const,
  assignmentManager: (params: Record<string, unknown>) => ['assignment-manager', params] as const,
  assignmentManagerStats: ['assignment-manager', 'stats'] as const,
  emailAnalysis: (shipmentId: string) => ['email-analysis', shipmentId] as const,
  crmCustomers: (params: Record<string, unknown>) => ['crm', 'customers', params] as const,
  crmCustomerDetail: (id: string) => ['crm', 'customers', 'detail', id] as const,
  crmCarriers: (params: Record<string, unknown>) => ['crm', 'carriers', params] as const,
  crmCarrierDetail: (id: string) => ['crm', 'carriers', 'detail', id] as const,
  crmAgents: (params: Record<string, unknown>) => ['crm', 'agents', params] as const,
  crmAgentDetail: (id: string) => ['crm', 'agents', 'detail', id] as const,
};
